### PR TITLE
Update class to lesson in documentation

### PR DESCRIPTION
**Pull request by muhammad-khair**
Changes made:
- Change `class` to `lesson` in documentation
- Change syntax for `enroll` and `unenroll` commands
  - From `enroll INDEX c/CLASS` to `enroll INDEX l/LESSON`

TODO:
- Update user stories to match as well

### CODE REVIEW

**Comment by Timothyoung97** [comment]
LGTM

**Comment by Timothyoung97** [comment]
LGTM

**Review by Timothyoung97 — COMMENTED** [review]
Very good

**Review by Timothyoung97 — APPROVED** [review]

**Review by eezj35 — APPROVED** [review]
LGTM

**Pull request merged**
